[package]
name = "red_js_interpreter"
version = "0.1.0"
edition = "2024"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
allow_attributes = "warn"
missing_const_for_fn = "deny"
unused_enumerate_index = "deny"
as_underscore = "deny"
str_to_string = "deny"
too_many_lines = "deny"
todo = "warn"
get_unwrap = "warn"
unwrap_used = "warn"
unwrap_in_result = "warn"
map_unwrap_or = "warn"

[dependencies]
redgex = "=0.3"
rand = "=0.10"

[dev-dependencies]
serial_test = "=4.0"
