name: Cargo test

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install nightly Rust
        run: rustup toolchain install nightly --profile minimal

      - name: Run cargo test
        run: cargo +nightly test
